import assert from 'node:assert/strict';
const base=process.env.COOKED_TEST_URL||'http://127.0.0.1:3000';
const request=(path,init)=>fetch(base+path,init);
const post=(path,body)=>request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
for(const path of ['/','/leaderboard','/bid?rank=4']) assert.equal((await request(path)).status,200,path);
const most=await (await request('/api/leaderboards/websites?mode=most')).json();
const least=await (await request('/api/leaderboards/websites?mode=least')).json();
assert(most.entries.length>=2,'Run two real local roasts before this smoke check.');
assert.deepEqual(most.entries.map(e=>e.totalScore),most.entries.map(e=>e.totalScore).sort((a,b)=>b-a));
assert.deepEqual(least.entries.map(e=>e.totalScore),least.entries.map(e=>e.totalScore).sort((a,b)=>a-b));
assert.equal(new Set(most.entries.map(e=>e.hostname)).size,most.entries.length);
const entry=most.entries[0], other=most.entries[1];
const started=Date.now(); const cached=await (await post('/api/analyses',{url:entry.hostname})).json();
assert.equal(cached.cached,true); assert.equal(cached.slug,entry.slug); const cacheMs=Date.now()-started;
assert.equal((await request('/r/'+entry.slug)).status,200);
assert.equal((await request('/challenge/'+entry.slug)).status,200);
const compared=await (await request(`/r/${other.slug}?vs=${entry.slug}`)).text();
assert(compared.includes('Challenge comparison')); assert(compared.includes(entry.hostname)); assert(compared.includes(other.hostname));
const png=await request('/api/share/'+entry.slug); assert.equal(png.headers.get('content-type'),'image/png');
const bytes=Buffer.from(await png.arrayBuffer()); assert.equal(bytes.subarray(1,4).toString(),'PNG'); assert.equal(bytes.readUInt32BE(16),1200); assert.equal(bytes.readUInt32BE(20),630);
assert.equal((await request('/api/share/not-a-result')).status,404);
assert.equal((await post('/api/analyses',{url:'http://127.0.0.1'})).status,400);
assert.equal((await request('/api/analyses/not-a-result/status')).status,404);
assert.equal((await post('/api/webhooks/razorpay',{})).status,400);
console.log(`PASS: real result routes, challenge comparison, exact ordered leaderboards, 1200×630 PNG card, cache (${cacheMs}ms), invalid URL, missing-result and invalid-payment errors.`);
